# Generated by Django 4.2.23 on 2025-08-17 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('color', models.CharField(max_length=64)),
                ('interpretation', models.TextField()),
                ('negative', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('sentiment_score', models.FloatField(default=0)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='myapp.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='myapp.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='myapp_analy_user_id_abd07d_idx')],
            },
        ),
    ]
