# Generated by Django 4.2.23 on 2025-09-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_journalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='myapp.analysis'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_analysis', to='myapp.journalentry'),
        ),
    ]
