# Generated by Django 4.2.23 on 2025-09-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_journalentry_analysis_alter_analysis_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='myapp.user'),
        ),
    ]
