# Generated by Django 4.2.24 on 2025-10-07 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_analysis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_analyses', to='myapp.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='myapp_cumul_user_id_387db1_idx')],
            },
        ),
    ]
