# Generated by Django 4.2.24 on 2025-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cumulativeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeanalysis',
            name='doctor_personality',
            field=models.TextField(blank=True, default=''),
        ),
    ]
