# Generated by Django 4.2.24 on 2025-10-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_workflowexecution_workflowstep_stepcitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeanalysis',
            name='workflow_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumulative_analyses', to='myapp.workflowexecution'),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='workflow_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_question', to='myapp.workflowexecution'),
        ),
    ]
