# Generated by Django 4.2.24 on 2025-10-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeanalysis',
            name='weights',
            field=models.JSONField(default=dict),
        ),
    ]
