# Generated by Django 4.2.24 on 2025-10-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cumulativeanalysis_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='weights',
            field=models.JSONField(default=dict),
        ),
    ]
