# Generated by Django 4.2.24 on 2025-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customquestion_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='doctor_personality',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='weights',
            field=models.JSONField(default=dict),
        ),
    ]
