# Generated by Django 4.2.24 on 2025-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_analysis_doctor_personality_analysis_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='symbols',
            field=models.JSONField(default=list),
        ),
    ]
