# Generated by Django 4.2.24 on 2025-10-10 23:50

from django.db import migrations, models
import django.db.models.deletion
import myapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_analysis_symbols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='archetype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='personality_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='prompt_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='tone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='weights',
            field=models.JSONField(default=myapp.models.default_doctor_weights),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_personality', models.TextField(blank=True, default='')),
                ('doctor_image', models.TextField(blank=True, default='')),
                ('personality_type', models.TextField(blank=True, default='')),
                ('occupation', models.TextField(blank=True, default='')),
                ('weights', models.JSONField(default=myapp.models.default_settings_weights)),
                ('doctor_influence', models.FloatField(default=0.7)),
                ('astrology', models.JSONField(default=dict)),
                ('medical_history', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='myapp.doctorprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myapp.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='myapp_setti_user_id_976133_idx')],
            },
        ),
    ]
