# Generated by Django 4.2.24 on 2025-11-03 03:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_doctorprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('accuracy', models.BooleanField(blank=True, null=True)),
                ('relevance', models.BooleanField(blank=True, null=True)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.analysis')),
                ('cumulative_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.cumulativeanalysis')),
                ('custom_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.customquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
            options={
                'indexes': [models.Index(fields=['analysis'], name='myapp_analy_analysi_a573db_idx'), models.Index(fields=['rating'], name='myapp_analy_rating_2ebf30_idx'), models.Index(fields=['created_at'], name='myapp_analy_created_080398_idx')],
                'unique_together': {('analysis', 'user')},
            },
        ),
    ]
