# Generated by Django 4.2.24 on 2025-11-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_analysisfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfeedback',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='myapp.analysis'),
        ),
    ]
