# Generated by Django 4.2.24 on 2025-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_analysisfeedback_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
